version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
        #       - setup_remote_docker:
        #           docker_layer_caching: true
      - run:
          name: Setup AWS CLI
          command: |
            curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
            unzip awscli-bundle.zip
            sudo ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws
      - run:
          name: Setup goss & dgoss
          command: |
            curl -L https://github.com/aelsabbahy/goss/releases/download/v0.3.6/goss-linux-amd64 -o ${HOME}/bin/goss
            chmod +x ${HOME}/bin/goss
            export GOSS_PATH=${HOME}/bin/goss
            curl -L https://raw.githubusercontent.com/aelsabbahy/goss/master/extras/dgoss/dgoss -o ${HOME}/bin/dgoss
            chmod +x ${HOME}/bin/dgoss
      - run:
          name: Build Image
          command: |
            docker build -t httpd . 
      - run:
          name: Run Tests
          command: |
            dgoss run httpd /usr/sbin/httpd -DFOREGROUND
            #      - run:
            #          name: Push Docker image to AWS ECR
            #          command: |
            #            docker build -t inokappa/$IMAGE_NAME:$TAG .
            #            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
            #            docker push inokappa/$IMAGE_NAME:$TAG
      - run:
          name: "Login to AWS ECR"
          command: eval $(aws ecr get-login --no-include-email)
            #       - run:
            #           name: "Build & Push Docker Image"
            #           command: |
            #             docker build -t $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/my-app:latest -t $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/my-app:$CIRCLE_SHA1 .
            #             docker push $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/my-app:$CIRCLE_SHA1
